### ISSUE TITLE
Suggestion: add Github project description

### ISSUE THREAD

**Issue by BrainCrumbz** [CarteKiwi/Toastinet#1]
We cannot provide this by way of forking, or we'd do that:

![image](https://cloud.githubusercontent.com/assets/3185573/8379421/41720f74-1c20-11e5-880a-f889b8ef61f0.png)

As an example, I guess this would do: "A simple WPF UI control that emulates Windows Phone toast notifications"

**Comment by CarteKiwi** [comment]
Done ;)
